annotations:
  category: CMS
apiVersion: v2
appVersion: 6.1.1
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
description: WordPress is the world's most popular blogging and content management platform. Powerful yet simple, everyone from students to global corporations use it to build beautiful, functional websites.
engine: gotpl
home: https://github.com/bitnami/charts/tree/main/bitnami/wordpress
icon: https://bitnami.com/assets/stacks/wordpress/img/wordpress-stack-220x234.png
keywords:
  - application
  - blog
  - cms
  - http
  - php
  - web
  - wordpress
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: wordpress
sources:
  - https://github.com/bitnami/containers/tree/main/bitnami/wordpress
  - https://wordpress.org/
version: 0.0.2
